export const storeProducts = [
    {
        id: 1,
        name: "armor pro / armor pro black",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/08/armor-pro.jpg',
        price: 1,
        company: 'cougar',
        details: 'COUGAR Armor PRO is the perfect seat for professional level gamers. This swivelling gaming chair is a fully adjustable throne that will satisfy the most demanding gamers. With a steel frame, high-quality components for extrdurability and loads of options to fine tune it to your needs, COUGAR Armor PRO is ready for battle.',
        inCart: false,
        count: 0,
        total: 0,
        category:'gaming thrones',
        isNewProduct:true
    },
    {
        id: 2,
        name: "armor pro titan / armor pro titan royal",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/08/armor-pro-titan.jpg',
        price: 1,
        company: 'cougar',
        details: 'ARMOR TITAN PRO is the perfect gaming throne for those who want to enjoy their games in absolute comfort while enjoying a visually attractive gaming chair. Endowed an extra-large build and with support for up to 160kg, plenty of adjustment options and top-quality materials, if you’re looking for the best gaming chair, you’re looking for ARMOR TITAN PRO!',
        inCart: false,
        count: 0,
        total: 0,
        category:'gaming thrones',
        isNewProduct:true
    },
    {
        id: 3,
        name: "700k evo",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/08/products_700k_evo.png',
        price: 1,
        company: 'cougar',
        details: 'With Surpassion RX, we have done what many thought to be impossible: we have merged a wired gaming mouse’s accuracy and reliability with the freedom of a wireless gaming mouse. See and believe.',
        inCart: false,
        count: 0,
        total: 0,
        category:'keyboards',
        isNewProduct:true
    },
    {
        id: 4,
        name: "700m evo esports",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2020/01/products_700m_evo_esports.png',
        price: 1,
        company: 'cougar',
        details: 'The final evolution of the gaming mouse world’s alpha predator. Taking all the customization, ergonomics and extended functionality that made 700M a winner, 700M EVO eSPORTS brings in a robust new optical sensor (Pixart PMW3389), further ergonomic enhancements and a new look to rule the online arenas.',
        inCart: false,
        count: 0,
        total: 0,
        category:'mice',
        isNewProduct:true
    },
    {
        id: 5,
        name: "minus xc",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/09/products_minos_xc.png',
        price: 1,
        company: 'cougar',
        details: 'MINOS XC + SPEED XC is a nimble and powerful gaming combo,ideal for those who enjoy an agile gaming experience.',
        inCart: false,
        count: 0,
        total: 0,
        category:'mice',
        isNewProduct:true
    },
    {
        id: 6,
        name: "phontum pro",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/12/products_Phontum_pro.jpg',
        price: 1,
        company: 'cougar',
        details: 'Phontum Pro brings you top-end audio quality in a highly comfortable design that includes two earpad (fabric and soft protein leather) sets to adapt itself to each situation. Endowed with COUGAR’s graphene diaphragm technology and a dual chamber system, this headset is the dream of an audiophile come true.',
        inCart: false,
        count: 0,
        total: 0,
        category:'headsets',
        isNewProduct:false
    },
    {
        id: 7,
        name: "surpassion rx",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/09/products_surpassion-rx.png',
        price: 1,
        company: 'cougar',
        details: 'With Surpassion RX, we have done what many thought to be impossible: we have merged a wired gaming mouse’s accuracy and reliability with the freedom of a wireless gaming mouse. See and believe.',
        inCart: false,
        count: 0,
        total: 0,
        category:'mice',
        isNewProduct:false
    },
    {
        id: 8,
        name: "vantar mx",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2019/08/products_vantarmx.png',
        price: 1,
        company: 'cougar',
        details: 'COUGAR Vantar MX is a keyboard for the committed gamer. With mechanical switches, a fully customizable per-key RGB backlight and one of the sturdiest keyboard designs the world has seen, everything you need to dominate your opponents is here.',
        inCart: false,
        count: 0,
        total: 0,
        category:'keyboards',
        newProduct:true
    },
    {
        id: 9,
        name: "ranger",
        img: 'https://cougargaming.com/_cgrwdr_/wwdpp/wp-content/uploads/2020/03/ranger.png',
        price: 1,
        company: 'cougar',
        details: 'Ranger provides with the full range of comfort for console gamers, mobile gamers,handheld gamers or PC gamers. We use premium materials, such as steel frame,high-quality components, foldable footrest, and tilted backrest. Ranger brings you the comfort you need to thoroughly enjoy long gaming sessions. Ranger is ready for fight!',
        inCart: false,
        count: 0,
        total: 0,
        category:'gaming thrones',
        newProduct:true
    },
];

export const detailProduct = {
    id: 108,
    title: "",
    img: '',
    price: 0,
    company: '',
    info: '',
    inCart: false,
    count: 0,
    total: 0,
}